AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CodePipeline for Python Tic Tac Toe Application

Resources:
  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: MyTicTacToePipeline
      RoleArn: arn:aws:iam::YOUR_ACCOUNT_ID:role/YourCodePipelineRole
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              Configuration:
                RepositoryName: YourCodeCommitRepository
                BranchName: master
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: YourCodeBuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
        - Name: Package
          Actions:
            - Name: PackageAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: YourPackageCodeBuildProject
              InputArtifacts:
                - Name: BuildOutput
              OutputArtifacts:
                - Name: PackageOutput
              RunOrder: 2
        - Name: Deploy
          Actions:
            - Name: DeployAction
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: ElasticBeanstalk
              Configuration:
                ApplicationName: YourElasticBeanstalkApplication
                EnvironmentName: YourElasticBeanstalkEnvironment
                VersionLabel: YourApplicationVersion
              InputArtifacts:
                - Name: PackageOutput
              RunOrder: 1

Parameters:
  YourCodeCommitRepository:
    Type: String
  YourCodeBuildProject:
    Type: String
  YourPackageCodeBuildProject:
    Type: String
  YourElasticBeanstalkApplication:
    Type: String
  YourElasticBeanstalkEnvironment:
    Type: String
  YourApplicationVersion:
    Type: String

Outputs:
  PipelineName:
    Value: !Ref MyCodePipeline
